FROM openjdk:8u272-slim
LABEL author="qtdevops"
ADD https://refferance.s3.us-east-2.amazonaws.com/spring-petclinic-2.4.2.jar ./spring-petclinic-2.4.2.jar
EXPOSE 8080
ENTRYPOINT [ "echo" ]
CMD [ "echo", "hello-world" ]