FROM openjdk:8
LABEL author="qtdevops"
LABEL organization="learning thoughts"
RUN wget https://refferance.s3.us-east-2.amazonaws.com/spring-petclinic-2.4.2.jar
EXPOSE 8080
CMD [ "java", "-jar", "spring-petclinic-2.4.2.jar" ]